In [2]:
def create_lookup_table(self):
        lookup_table = {}
        for spo_path in self.spo_file_paths:
            print("[KnowledgeGraph] Loading spo from {}".format(spo_path))
            with open(spo_path, 'r', encoding='utf-8') as f:
                for line in f:
                    try:
                        subj, pred, obje = line.strip().split("\t")    
                    except:
                        print("[KnowledgeGraph] Bad spo:", line)
                    if self.predicate:
                        value = pred + obje
                    else:
                        value = obje
                    if subj in lookup_table.keys():
                        lookup_table[subj].add(value)
                    else:
                        lookup_table[subj] = set([value])
        return lookup_table

In [3]:
create_lookup_table('kgs/kg_anatomy3kAndAtelectasis.spo')

AttributeError: 'str' object has no attribute 'spo_file_paths'

In [4]:
import brain.config as config

In [9]:
config.KGS.get('HowNet','HowNet')

'/Users/zm_leng/ML/BA/K-BERT/brain/kgs/HowNet.spo'

In [20]:
lookup_table = {}
spo_file_paths= ['./brain/kgs/kg_anatomy3kAndAtelectasis.spo']
predicate = False
for spo_path in spo_file_paths:
    print("[KnowledgeGraph] Loading spo from {}".format(spo_path))
    with open(spo_path, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                subj, pred, obje = line.strip().split("\t")    
            except:
                print("[KnowledgeGraph] Bad spo:", line)
            if predicate:
                value = pred + obje
            else:
                value = obje
            if subj in lookup_table.keys():
                lookup_table[subj].add(value)
            else:
                lookup_table[subj] = set([value])

[KnowledgeGraph] Loading spo from ./brain/kgs/kg_anatomy3kAndAtelectasis.spo


In [22]:
lookup_table

{'x_name': {'y_name'},
 'Atelectasis': {'22q11.2_deletion_syndrome',
  'Abnormal_lung_morphology',
  'Acetaminophen',
  'Amobarbital',
  'Amphotericin_B',
  'Aprotinin',
  'Azacitidine',
  'Beemer-Langer_syndrome',
  'Bivalirudin',
  'Bortezomib',
  'Busulfan',
  'CHAND_syndrome',
  'Cevimeline',
  'Dexibuprofen',
  'Dexmedetomidine',
  'Donepezil',
  'Ertapenem',
  'Esmolol',
  'Everolimus',
  'Farber_lipogranulomatosis',
  'Fluoxetine',
  'Fosphenytoin',
  'Hyper-IgE_recurrent_infection_syndrome_1',
  'Ibuprofen',
  'Levofloxacin',
  'Linear_atelectasis',
  'Memantine',
  'Morphine',
  'Mycophenolic_acid',
  'Nitric_Oxide',
  'Ofloxacin',
  'Olanzapine',
  'Phenytoin',
  'Porfimer_sodium',
  'Posaconazole',
  'Pregabalin',
  'Propafenone',
  'Remifentanil',
  'Ropivacaine',
  'Rounded_atelectasis',
  'Rowley-Rosenberg_syndrome',
  'Sirolimus',
  'Tacrolimus',
  'Urofollitropin',
  'Venlafaxine',
  'WHIM_syndrome',
  'Waardenburg_syndrome',
  'Zygomycosis',
  'acute_interstitial_pneum

In [4]:
{1,2,3}

TypeError: unhashable type: 'list'

In [10]:
import torch

In [7]:
labels_sets = [{1,2,3},{1,2,3},{1,2,3},{1,2,3},{1,2,3},{1,2,3},{1,2,3},{1,2,3},{1,2,3},{1,2,3},{1,2,3},{1,2,3},{1,2,3}]


In [11]:
labels_nums = [len(labels_set) for labels_set in labels_sets] 
confusions = [torch.zeros(num, num, dtype=torch.long) for num in labels_nums]

In [12]:
confusions

[tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]])]

In [13]:
labels_nums

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [15]:
confusions[4].size()

torch.Size([3, 3])